### ISSUE TITLE
Window close button is inactive

### ISSUE THREAD

**Issue by NamesMark** [TheBestTvarynka/Dataans#47]
I would like it to be active and minimize the app. Since `WindowEvent::CloseRequested` is already intercepted, the close button should indeed minimize the window as intended, so there is no reason to disable it.

**Comment by TheBestTvarynka** [comment]
I did it on purpose. In our case, the close button closes the UI but the app still running and the windows can be opened again from the system tray:

![image](https://github.com/user-attachments/assets/bafe4a89-d0e6-471e-9e55-d1581db4609f)

I decided to hide this button because its behavior is different. Usually, the user expects to close the entire app using the close button, but in our case, it only closes the window but not the app.

What do you think? (I'm open for communication and changes, so if you resist, then we will enable it again 😃)
